# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pokes',
            field=models.IntegerField(default=0),
        ),
    ]
