# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_pokes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pokes',
        ),
    ]
